name: build

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

env:
  SBT: ./sbt
  JDK: 1.8
  REPO_SLUG: ${{ github.repository }}
  ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}
  GITHUB_ACTOR: precog-bot
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.12.10]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up JDK ${{ env.JDK }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK }}
      - name: Setup Git Actor
        run: git config github.actor precog-bot
      - name: Run Tests
        run: $SBT ++${{ matrix.scala }} ci
      - name: Upload working directory
        uses: actions/upload-artifact@v1
        with:
          name: working-dir
          path: .

  publish-and-tag:
    name: Publish and Tag
    needs: [build]
    if: github.event_name != 'pull_request' && (contains(github.ref, 'backport/v.*') || contains(github.ref, 'master'))
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Download working directory
        uses: actions/download-artifact@v1
        with:
          name: working-dir
      - name: Set up JDK ${{ env.JDK }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK }}
      - name: Install ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Setup Git Actor
        run: git config github.actor precog-bot
      - name: Run transferCommonResources
        run: $SBT transferCommonResources
      - name: Export common secrets
        run: $SBT exportSecretsForActions
      - name: Transfer Publish and Tag Resources
        run: $SBT transferPublishAndTagResources
      - name: Common setup
        run: ./scripts/commonSetup
      - name: Publish Tag
        run: scripts/publishAndTag 'precog/quasar'

  auto-merge:
    name: Auto Merge
    if: github.event_name == 'pull_request' && contains(github.head_ref, 'version-bump')
    needs: [build]
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        scala: [2.12.10]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Download working directory
        uses: actions/download-artifact@v1
        with:
          name: working-dir
      - name: Install ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Setup Git Actor
        run: git config github.actor precog-bot
      - name: Install common resources
        run: $SBT transferCommonResources
      - name: Export common secrets
        run: $SBT exportSecretsForActions
      - name: Run common setup
        run: ./scripts/commonSetup
      - name: Set env vars
        run: |
          echo ::set-env name=CLONE_DIR::$(mktemp -d "/tmp/precog-bump.XXXXXXXX")
          echo ::set-env name=PR_NUMBER::$(echo "$GITHUB_REF" | cut -d'/' -f3)
          echo ::set-env name=PULL_REQUEST::$(echo "true")
      - name: Check auto merge
        run: ./scripts/checkAndAutoMerge
